# Generated by Django 5.1.7 on 2025-03-25 20:18

import apps.lojas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='telefone',
            field=models.CharField(default=2, max_length=11, validators=[apps.lojas.models.validate_telefone]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[apps.lojas.models.validate_cnpj]),
        ),
    ]
