# Generated by Django 5.1.7 on 2025-03-25 19:37

import apps.motoboys.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=11, validators=[apps.motoboys.models.validate_telefone])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('placa_moto', models.CharField(max_length=7, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motoboys', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Motoboy',
                'verbose_name_plural': 'Motoboys',
                'ordering': ['nome'],
            },
        ),
    ]
