# Generated by Django 5.1.7 on 2025-03-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ativo',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
