# Generated by Django 5.1.7 on 2025-03-25 23:41

import apps.entregas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0002_loja_telefone_alter_loja_cnpj'),
        ('motoboys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('data_entrega', models.DateTimeField(validators=[apps.entregas.models.validate_data_entrega])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('entregue', models.BooleanField(default=False)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='lojas.loja')),
                ('motoboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='motoboys.motoboy')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['data_entrega'],
            },
        ),
    ]
